feature: implemented main page
bridge-to-bits/b2b-web pull request #1
Opened 2024-11-23 16:52 UTC by dmykyr

- created main page components
  - Banner
  - CardInfo
  - Hero
  - PerformerCard
  - PerformersSection
  - ProducerCard
  - ProducersSection
  - SectionHeader
  - SocialsList
 - hardcoded data lists of producers and performers
 - added several photos for testing purpose
 - specified project color palette in globals.css
 - implemented footer

2024-11-23 19:56 UTC, sifes requested changes

2024-11-23 19:56 UTC, sifes commented on src/app/(application)/page.tsx
> +    genres: "EDM",
це ти потім будеш фетчити, поки мокові данні?

2024-11-23 19:56 UTC, sifes commented on src/app/globals.css
> +    --background-top: #030303;
чому white це сірий

2024-11-23 19:56 UTC, sifes commented on src/app/globals.css
> +    --background-bottom: #1F1E1E;
що за кольори -background-bottom і -background-top, чому вони так називаються, як це колір background-top

2024-11-23 19:56 UTC, sifes commented on src/components/layout/components/Footer.tsx
> +        <div className="flex flex-col md:flex-row gap-[40px] text-[var(--white)] text-center md:text-left">
1)gap-10 
2)text-white

2024-11-23 19:56 UTC, sifes commented on src/components/layout/components/Footer.tsx
> +          <p className="mt-[20px] text-[16px]">Тех підтримка?</p>
text-md це раз, і він такий за замовчуванням

2024-11-23 19:56 UTC, sifes commented on src/components/layout/components/Footer.tsx
> +                <a href="/about" className="hover:text-orange-500">
ні, не link з нексту, ти не повинен використовувати <a/>

2024-11-23 19:56 UTC, sifes commented on src/components/layout/components/Footer.tsx
> +              <Github className="w-[24px] h-[24px] hover:text-orange-500" />
h-6 w-6

2024-11-23 19:56 UTC, sifes commented on src/components/pages/main/Banner.tsx
> +      <h1 className="text-4xl font-bold mb-4">Bridge to Bits</h1>
немає сенсу в окремий компонент тільки його
тут 2 варіанти, або декомпозувати весь компонент, щоб було гарно і класно, або не декомпозувати нічого, бо тут онлі верстка поки, то ж можна засунути в один компонент і так виносити як тут немає сенсу (орієнтуйся на логіку або на великий розмір. тут немає ні того, ні того, отже виносити це в окремий компонент сенсу немає)

2024-11-23 19:56 UTC, sifes commented on src/components/pages/main/CardInfo.tsx
> +      className="w-full aspect-[4] rounded-[25px] bg-cover bg-center relative flex flex-col justify-center"
що за аспект і rounded-md або який там буде відповідати

2024-11-23 19:56 UTC, sifes commented on src/components/pages/main/Hero.tsx
> +        <div className="text-center text-white">
тут вже побільше контенту, є сенс виносити, виглядає солідніше, але тоді можеш абсолютно всю сторінку декомпозувати, шоб виглядало краще

2024-11-23 19:56 UTC, sifes commented on src/components/pages/main/PerformerCard.tsx
> +  const togglePlay = () => setIsPlaying((prev) => !prev);
нема сенсу виносити, можеш відразу в onCLick прописати

2024-11-23 19:56 UTC, sifes commented on src/components/pages/main/SectionHeader.tsx
> +const SectionHeader: React.FC<SectionHeaderProps> = ({ text }) => {
немає абсолютно жодного сенсу тут від пропсу цього. вище ти просто передаєш текст <SectionHeader text="Топ Виконавців" /> і ніби як використовуєш тільки в одному місці де передаєш ЗАХАРДКОДЕНЕ значення, чому просто не прописати його тут і позбутись пропсів?

2024-11-23 19:56 UTC, sifes commented on src/components/pages/main/SocialsList.tsx
> +      <Music className="w-[8%] h-[8%] text-[var(--white)] hover:text-orange-500 cursor-pointer" />
не прописуй іконкам відносну ширину і висоту, бо є якісь монітори 4000 в ширину, а висота 800, там це буде не пропорційно від слова зовсім (навіть якщо не враховувати це, то загалом на супер великих моніторах все одно їх робити більшими не треба, бо юзер або ближче сидить або там декілька монеторів або ще дещо)

2024-11-24 08:46 UTC, dmykyr commented on src/app/(application)/page.tsx
> +    genres: "EDM",
йеп, для тесту поки

2024-11-24 08:52 UTC, dmykyr commented on src/app/globals.css
> +    --background-bottom: #1F1E1E;
поміняв на 
`    --background-black-primary: #030303;
    --background-black-secondary: #1F1E1E;`

2024-11-24 09:30 UTC, dmykyr commented on src/components/pages/main/Banner.tsx
> +      <h1 className="text-4xl font-bold mb-4">Bridge to Bits</h1>
Це я компоненту забув прибрати, там це все є в компоненті Hero яка більша трохи і вже уособлює повністю всю "секцію" сторінки, а не якусь частину

2024-11-25 12:58 UTC, sifes requested changes

2024-11-25 12:58 UTC, sifes commented on src/app/(application)/page.tsx
> +import Banner from '@/components/pages/main/Hero';
Banner але з Hero (default imports йдуть нахуй)

2024-11-25 12:58 UTC, sifes commented on src/app/api/users/users-api.ts
> +      const response = await axios.get(`${API_BASE_URL}/performers`, { params });
створи instance.ts (подивись на фа або на прийомці), він дозволить не прокидувати кожен раз API_BASE_URL

2024-11-25 12:58 UTC, sifes commented on src/components/layout/components/Footer.tsx
> +        <div className="flex flex-col items-center md:items-end text-[var(--white)] mt-5 md:mt-0">
text-[var(--white)]

2024-11-25 12:58 UTC, sifes commented on src/components/layout/components/Footer.tsx
> +          <p className="text-[16px]">+00000000000</p>
text-[16px]

2024-11-25 12:58 UTC, sifes commented on src/components/layout/components/Footer.tsx
> +    <footer className="w-full bg-[var(--header-footer)] py-10 px-[5%]">
bg-[var(--header-footer)]

2024-11-25 12:58 UTC, sifes commented on src/components/pages/main/CardInfo.tsx
> +      <div className="pl-[5%] text-[var(--white)]">
text-[var(--white)]

2024-11-25 12:58 UTC, sifes commented on src/components/pages/main/PerformersSection.tsx
> +    fetchPerformers();
nope, зроби це через useQuery

2024-11-25 12:58 UTC, sifes commented on src/components/pages/main/ProducersSection.tsx
> +    fetchPerformers();
і тут теж через useQuery

2024-11-25 15:40 UTC, merged

2024-11-25 15:54 UTC, sifes commented on src/app/globals.css
> +    --background-header-footer: #202229;
-background-header-footer

2024-11-25 15:54 UTC, sifes commented on src/components/layout/components/Footer.tsx
> +                <Link href="/player" className="hover:text-orange-500">
зроби краще массив як у мене в Links і зроби ітерацію по ньому. Додай text i href, так буде зрозуміліше, що відбувається

2024-11-25 15:54 UTC, sifes commented on src/components/layout/components/Footer.tsx
> +                  Конфіденційність
і тут також

2024-11-25 15:54 UTC, sifes commented on src/components/layout/components/Footer.tsx
> +            >
і тут
але тут icon i href

2024-11-25 15:54 UTC, sifes commented on src/components/pages/main/PerformerCard.tsx
> +              <Play className="text-[var(--orange)]" />
text-[var(--orange)]

2024-11-25 15:54 UTC, sifes commented on src/components/pages/main/PerformerCard.tsx
> +            className="bg-foreground ml-[15px] rounded-full w-[40px] h-[40px] flex items-center justify-center"
h-10 w-10

2024-11-25 15:54 UTC, sifes commented on src/components/pages/main/PerformersSection.tsx
> +    staleTime: 300000,
це тобі не треба

2024-11-25 15:54 UTC, sifes commented on src/components/pages/main/PerformersSection.tsx
> +      const query = { pageNumber: 1, pageSize: 6 };
query прибери, і додай відразу в фетч

2024-11-25 15:54 UTC, sifes commented on src/components/pages/main/PerformersSection.tsx
> +      const performersPaginatedData = await UsersApi.getPerformers(query);
в самій функції повертай просто queryFn: async () => UsersApi.getPerformers(query)

а внизу додай select: (data) => data.data

2024-11-25 15:54 UTC, sifes commented on src/components/pages/main/PerformersSection.tsx
> +    return <div className="text-center">Loading...</div>;
у тебе є Loader

2024-11-25 15:54 UTC, sifes commented on src/components/pages/main/ProducerCard.tsx
> +     producer
полетіло форматування

2024-11-25 15:54 UTC, sifes commented on src/components/pages/main/ProducerCard.tsx
> +    <div className="w-full aspect-[4] border-[4px] border-[var(--background-header-footer)] p-[20px] rounded-[25px] shadow-md">
border-[var(--background-header-footer)]

2024-11-25 15:54 UTC, sifes commented on src/components/pages/main/ProducerCard.tsx
> +    <div className="w-full aspect-[4] border-[4px] border-[var(--background-header-footer)] p-[20px] rounded-[25px] shadow-md">
p-[20px] => p-5; rounded-[25px] => rounded-xl (приблизно)

2024-11-25 15:54 UTC, sifes commented on src/components/pages/main/ProducersSection.tsx
> +      const performersPaginatedData = await UsersApi.getProducers(query);
the same shit that i have wrote above

2024-11-25 15:54 UTC, sifes commented on src/components/pages/main/SocialsList.tsx
> +            key={index}
НЕ роби key={index}
візьми краще якесь значення з social (будь-яке унікальне, це може бути social.link)